
openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: API documentation for the e-commerce system
servers:
  - url: http://localhost:5000
paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        "201":
          description: User created successfully

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful

  /api/products:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        "200":
          description: List of products
    post:
      tags:
        - Products
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                categoryId:
                  type: integer
      responses:
        "201":
          description: Product created

  /api/products/{id}:
    get:
      tags:
        - Products
      summary: Get product by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Product details
    put:
      tags:
        - Products
      summary: Update a product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                categoryId:
                  type: integer
      responses:
        "200":
          description: Product updated
    delete:
      tags:
        - Products
      summary: Delete a product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Product deleted

  /api/products/{productId}/reviews:
    post:
      tags:
        - Reviews
      summary: Create a review for a product
      parameters:
        - in: path
          name: productId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        "201":
          description: Review added

  /api/orders:
    post:
      tags:
        - Orders
      summary: Place an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shippingAddress:
                  type: string
                paymentMethod:
                  type: string
      responses:
        "201":
          description: Order created
